name: Staging build, test & deploy app

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - TestFunctionApp/**/*

env:
  AZURE_FUNCTIONAPP_NAME: silly-function-app
  AZURE_FUNCTIONAPP_RESOURCEGROUP: github-migration-npe
  AZURE_FUNCTION_APP_PACKAGE_PATH: './TestFunctionApp'
  DOTNET_VERSION: '6.0.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Build'
        shell: bash
        run: |
          dotnet build '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}' --configuration Release --output ./output

      - name: Download Azure Function app publishing profile
        id: az_funcapp_publishing_profile
        run: |
          echo "FUNCTION_APP_PUB_PROFILE=$(az functionapp deployment list-publishing-profiles --resource-group $AZURE_FUNCTIONAPP_RESOURCEGROUP --name $AZURE_FUNCTIONAPP_NAME --xml)" >> $GITHUB_ENV